// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package core

// Injectors from wire.go:

func initProject(r rdir, p pdir) *Project {
	viper := newViper()
	projectConfigImpl := newProjectConfig(viper, p)
	baseEnvImpl := newBaseEnv(r)
	project := newProjectInternal(p, projectConfigImpl, baseEnvImpl)
	return project
}
